version: '3.4'

services:
  db:
    image: postgres:13.4-alpine
    restart: always
    env_file:
      - ./.env.db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - ./.env
      - ./.env.db
    container_name: cloudpso_test
    command: ./manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/opt/code
    depends_on:
      - db

volumes:
  db_data:
